name: Build and Deploy payment microservice to Development

on:
  push:
    branches-ignore:
      - main  

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/microservices-python.yaml@main
    with:
      MICROSERVICE: payment
      IMAGE: payment
      NAMESPACE: payment-microservice
      RELEASE: payment
      WORKING_DIR: ./payment
      DOCKERFILE_PATH: .
    secrets: inherit